# Church-on-Rails supports multiple database types.
#
# The database for running tests is always sqlite3.
# But for development and production it can be easily customised
# to your system by setting environment variables on the server,
# or in a config.application.yml file.
#
#   DB_ADAPTER:   sqlite3 | mysql2 | postgresql
#   DB_NAME:      your database name
#   DB_USER:      username
#   DB_PASSSWORD: ******
#
default: &default
  pool: 5
  timeout: 5000
  adapter: <%= ENV["DB_ADAPTER"] %>

  <% if ENV["DB_ADAPTER"] == 'sqlite3' %>
  database: db/<%= Rails.env %>.sqlite3

  <% elsif ENV["DB_ADAPTER"] == 'postgresql' %>
  encoding: unicode
  database: <%= ENV["DB_NAME"] %>
  username: <%= ENV["DB_USER"] %>
  password: <%= ENV["DB_PASSWORD"] %>

  <% elsif ENV["DB_ADAPTER"] == 'mysql2' %>
  encoding: utf8
  database: <%= ENV["DB_NAME"] %>
  username: <%= ENV["DB_USER"] %>
  password: <%= ENV["DB_PASSWORD"] %>
  host:     <%= ENV["DB_HOST"] || '127.0.0.1' %>
  port:     <%= ENV["DB_PORT"] || '3306' %>

  <% end %>

development:
  <<: *default

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test:
  adapter: sqlite3
  pool: 5
  timeout: 5000
  database: db/test.sqlite3

production:
  <<: *default
